version: '3'

services:
  influxdb:
    image: influxdb
    ports:
      - 8083:8083
      - 8086:8086
    environment:
      - INFLUXDB_DB=telegraf
      - INFLUXDB_USER=telegraf
      - INFLUXDB_USER_PASSWORD=telegraf
    volumes:
      - ./influxdb:/var/lib/influxdb
  
    restart: always

  telegraf:
    image: telegraf
    restart: always
    ports:
      - 8125:8125
      - 8094:8094
      - 162:162/udp
      - 8092:8092/udp
    links:
      - influxdb
    volumes:
      - ./mibs/:/usr/share/snmp/mibs/
      - ./telegraf.conf:/etc/telegraf/telegraf.conf

  grafana:
    image: grafana/grafana
    restart: always
    ports:
      - 3000:3000
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    links:
      - influxdb
    volumes:
      - ./grafana:/var/lib/grafana
